# Generated by Django 6.0.2 on 2026-03-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_address_student_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_date',
            new_name='date_joined',
        ),
    ]
