# Generated by Django 6.0.2 on 2026-03-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_admission_date_student_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_joined',
            new_name='admission_date',
        ),
    ]
