# Generated by Django 6.0.2 on 2026-03-10 19:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_alter_course_faculty'),
        ('departments', '0001_initial'),
        ('students', '0007_alter_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('library_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'ordering': ['-academic_year', 'course'],
                'unique_together': {('course', 'academic_year', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', 'student__name'],
                'unique_together': {('student', 'academic_year', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=30)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('received_by', models.CharField(blank=True, max_length=150, null=True)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.studentfee')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateField(default=django.utils.timezone.now)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fees', to='finance.studentfee')),
            ],
            options={
                'ordering': ['-added_on', '-id'],
            },
        ),
    ]
