# Generated by Django 6.0.2 on 2026-03-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinstallment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
