# Generated by Django 6.0.2 on 2026-03-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_faculty_salary_remove_faculty_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
    ]
