# Generated by Django 6.0.2 on 2026-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='TEMP', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='GENERAL', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='TEMP', max_length=100),
            preserve_default=False,
        ),
    ]
