# Generated by Django 6.0.2 on 2026-03-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_remove_subject_course_remove_subject_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('lecture_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='subjects.subjectassignment')),
            ],
            options={
                'ordering': ['day', 'lecture_number'],
                'unique_together': {('subject_assignment', 'day', 'lecture_number')},
            },
        ),
    ]
